### ISSUE TITLE
The two trained models on OpenWebText

### ISSUE THREAD

**Issue by zdaiot** [sosier/LLM_Token_Frequency_Feature#1]
"I trained two small character-level language models on the works of Shakespeare using Andrej Karpathy's [nanoGPT repo](https://github.com/karpathy/nanoGPT/tree/master)."

Hi, will you release the two trained models on OpenWebText for further studies? It would be truly appreciated. Thank you.

**Comment by sosier** [comment]
Hi @zdaiot, do you mean the models trained on Shakespeare? I didn't personally have the GPUs to train the larger models on OpenWebText.

**Comment by zdaiot** [comment]
> Hi @zdaiot, do you mean the models trained on Shakespeare? I didn't personally have the GPUs to train the larger models on OpenWebText.

Yes, I am referring to the models trained on Shakespeare. Is there any plan to share and release them? I believe it will really help, as many people might not be able to train one themseleves (including me :) ).

**Comment by sosier** [comment]
Gotcha, let me see what I can do. I've meaning to learn how to get trained models onto Hugging Face anyway. I'll try to look into it this weekend.

**Comment by sosier** [comment]
Okay, those two models are now up on Hugging Face [here](https://huggingface.co/sosier/nanoGPT-shakespeare-char-tied-weights) and [here](https://huggingface.co/sosier/nanoGPT-shakespeare-char-weights-not-tied).
